using Armory.Core;
using UnityEngine;

namespace Armory
{
    /// <summary>
    /// Which downloaded model stands in for each enemy kind, generated by Armory/Prepare Enemy Visuals and
    /// editable in the inspector. A kind with no usable row keeps the primitive placeholder, so the game still
    /// runs with a half-filled table and models can land one at a time.
    /// </summary>
    public sealed class EnemyVisuals : ScriptableObject
    {
        [System.Serializable]
        public sealed class Entry
        {
            public EnemyKind Kind;
            public GameObject Prefab;
            [Tooltip("Metres from the deck to the top of the model. 0 keeps the model's own import scale.")]
            public float Height = 2f;
            [Tooltip("Degrees to turn the model so it faces along +Z like the placeholder capsules do.")]
            public Vector3 EulerOffset;
            [Tooltip("Animator bool set while the enemy is moving, if the model ships a controller. Blank to skip.")]
            public string MovingParameter = "";

            /// <summary>False when the model should keep whatever scale it was imported at.</summary>
            public bool Rescales => Height > 0f;
        }

        public Entry[] Entries;

        /// <summary>The model authored for this kind, or null to fall back to the primitive placeholder.</summary>
        public Entry For(EnemyKind kind)
        {
            if (Entries == null) return null;
            foreach (var entry in Entries)
                if (entry != null && entry.Kind == kind && entry.Prefab != null) return entry;
            return null;
        }
    }
}
