using UnityEngine;

namespace Armory
{
    /// <summary>Build-safe model/clip references, generated by Armory/Prepare Hive Avatar Assets.</summary>
    public sealed class HiveAvatarAssets : ScriptableObject
    {
        /// <summary>Authored art prefab (chitin scales, organ sockets, animator controller). Preferred over Model.</summary>
        public GameObject Visual;
        /// <summary>Bare rigged FBX, still used when Visual is empty; the clips below only drive that path.</summary>
        public GameObject Model;
        public AnimationClip Idle, Walk, Attack, Spit, Death;
        public float Height = 14f;
    }
}
