using UnityEngine;

namespace Armory
{
    /// <summary>Build-safe model/clip references, generated by Armory/Prepare Hive Avatar Assets.</summary>
    public sealed class HiveAvatarAssets : ScriptableObject
    {
        public GameObject Model;
        public AnimationClip Idle, Walk, Attack, Spit, Death;
        public float Height = 14f;
    }
}
