using System;
using UnityEngine;

namespace Armory
{
    /// <summary>
    /// Name to prefab for everything under Assets/Game/Art/Effects, generated by Armory > Art > Build Effect
    /// Library. The prefabs live outside a Resources folder so the art builders can keep writing to their authored
    /// paths; this table is the one build-safe reference into them, and a missing row simply means no art plays.
    /// </summary>
    public sealed class EffectLibrary : ScriptableObject
    {
        [Serializable]
        public sealed class Entry
        {
            /// <summary>Prefab file name without the extension, e.g. "BossShockwave" or "Death_Grunt".</summary>
            public string Key;
            public GameObject Prefab;
        }

        public Entry[] Entries;

        public GameObject Find(string key)
        {
            if (Entries == null || string.IsNullOrEmpty(key)) return null;
            foreach (var entry in Entries)
                if (entry != null && entry.Prefab != null && string.Equals(entry.Key, key, StringComparison.OrdinalIgnoreCase))
                    return entry.Prefab;
            return null;
        }
    }
}
